name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
          matrix:
            os: ['ubuntu-latest', 'windows-latest', 'macOS-latest']
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: 'Start xvfb'
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
        if: success() && matrix.os == 'ubuntu-latest'
      - name: 'Compile'
        run: |
          npm ci
          npm run compile
        env:
          DISPLAY: ':99.0'
      - name: 'Test'
        run: |
          npm test
        env:
          DISPLAY: ':99.0'
